mark com.github.matsluni.aws-spi-akka-http as test
Trying to construct an aws client when depending on alpakka and the
aws sdk v2 library fails due to the following exception:

software.amazon.awssdk.core.exception.SdkClientException: Multiple HTTP
implementations were found on the classpath. To avoid non-deterministic
loading implementations, please explicitly provide an HTTP client via
the client builders, set the
software.amazon.awssdk.http.async.service.impl system property with the
FQCN of the HTTP service to use as the default, or remove all but one
HTTP implementation from the classpath

Excluding the akka spi http transitive dependency fixes the problem:

"com.lightbend.akka" %% "akka-stream-alpakka-dynamodb" % versions.alpakka exclude("com.github.matsluni", "aws-spi-akka-http")

Since this library is only used in examples, I suggest that we mark it
as a test dependency so that only users that explicitly include the akka
spi http client will run into this error.